name: 'paracelsus'
version: '1.0.0'
config-version: 2

profile: 'paracelsus'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # Date range for analysis
  start_date: '2024-01-01'
  end_date: '{{ run_started_at.strftime("%Y-%m-%d") }}'

models:
  paracelsus:
    # Staging models - 1:1 with sources
    staging:
      +materialized: view
      +schema: staging

    # Intermediate models - business logic
    intermediate:
      +materialized: view
      +schema: intermediate

    # Mart models - final fact/dimension tables
    marts:
      +materialized: table
      +schema: marts
