# ELT services: Meltano (Extract, Load, Transform) and data seeding

services:
  # Meltano ELT (Extract, Load, Transform) - unified container
  # Includes dbt-postgres utility for running dbt transforms
  meltano:
    build:
      context: ../meltano
      dockerfile: Dockerfile
    container_name: paracelsus-meltano
    restart: unless-stopped
    labels:
      com.paracelsus.component: "elt"
    env_file:
      - ../.env
    # Note: SSL cert for mock-hubspot is patched in entrypoint.sh
    # only for tap-hubspot's virtualenv, not globally
    volumes:
      - ../meltano:/project
      - ../dbt:/project/dbt  # Mount dbt project for dbt-postgres utility
      - meltano-data:/project/.meltano
      - hubspot-certs:/certs:ro  # Self-signed cert from mock-hubspot
    depends_on:
      oltp-db:
        condition: service_healthy
      olap-db:
        condition: service_healthy
      localstack:
        condition: service_healthy
      mock-hubspot:
        condition: service_healthy
    # DNS redirect: HubSpot API calls go to mock-hubspot via network alias
    # (api.hubapi.com alias defined in compose/mock-services.yml)
    # Entrypoint is defined in Dockerfile (installs SSL cert then runs CMD)

  # Synthetic data seeder
  seeder:
    build:
      context: ../synthetic_data
      dockerfile: Dockerfile
    container_name: paracelsus-seeder
    restart: "no"  # One-shot container, no restart
    labels:
      com.paracelsus.component: "elt"
    env_file:
      - ../.env
    depends_on:
      oltp-db:
        condition: service_healthy
      localstack:
        condition: service_healthy
    volumes:
      - ../synthetic_data:/app

volumes:
  meltano-data:
